apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: velero
      version: 3.1.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 10
